<?php

// Not an error.
echo PHP_VERSION;
echo intl_idna_variant_2003;

// Removed/deprecated constants.
echo FILEINFO_COMPRESS;
echo CURLOPT_CLOSEPOLICY;
echo CURLCLOSEPOLICY_LEAST_RECENTLY_USED;
echo CURLCLOSEPOLICY_LEAST_TRAFFIC;
echo CURLCLOSEPOLICY_SLOWEST;
echo CURLCLOSEPOLICY_CALLBACK;
echo CURLCLOSEPOLICY_OLDEST;
echo PGSQL_ATTR_DISABLE_NATIVE_PREPARED_STATEMENT;
echo INTL_IDNA_VARIANT_2003;
echo MCRYPT_MODE_ECB;
echo MCRYPT_MODE_CBC;
echo MCRYPT_MODE_CFB;
echo MCRYPT_MODE_OFB;
echo MCRYPT_MODE_NOFB;
echo MCRYPT_MODE_STREAM;
echo MCRYPT_ENCRYPT;
echo MCRYPT_DECRYPT;
echo MCRYPT_DEV_RANDOM;
echo MCRYPT_DEV_URANDOM;
echo MCRYPT_RAND;
