<?php
interface Baz {}
interface abstract {}
interface and {}
interface array {}
interface as {}
interface break {}
interface callable {}
interface case {}
interface catch {}
interface class {}
interface clone {}
interface const {}
interface continue {}
interface declare {}
interface default {}
interface do {}
interface else {}
interface elseif {}
interface enddeclare {}
interface endfor {}
interface endforeach {}
interface endif {}
interface endswitch {}
interface endwhile {}
interface extends {}
interface final {}
interface finally {}
interface for {}
interface foreach {}
interface function {}
interface global {}
interface goto {}
interface if {}
interface implements {}
interface interface {}
interface instanceof {}
interface insteadof {}
interface namespace {}
interface new {}
interface or {}
interface private {}
interface protected {}
interface public {}
interface static {}
interface switch {}
interface throw {}
interface trait {}
interface try {}
interface use {}
interface var {}
interface while {}
interface xor {}
interface list {}
interface unset {}
interface die {}
interface empty {}
interface include_once {}
interface include {}
interface return {}
interface yield {}
interface echo {}
interface eval {}
interface exit {}
interface isset {}
interface print {}
interface require_once {}
interface __CLASS__ {}
interface __DIR__ {}
interface __FILE__ {}
interface __FUNCTION__ {}
interface __METHOD__ {}
interface __NAMESPACE__ {}
