name: Remove outdated labels

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    types:
      - closed
  issues:
    types:
      - closed

# Permissions should be configured at the job level.
permissions: {}

jobs:
  on-pr-merge:
    permissions:
      pull-requests: write # To remove PR labels.

    if: github.repository_owner == 'PHPCompatibility' && github.event.pull_request.merged == true

    name: Clean up labels on PR merge
    runs-on: ubuntu-latest

    steps:
      - uses: mondeja/remove-labels-gh-action@b7118e4ba5dca74acf1059b3cb7660378ff9ab1a # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            PR: quick merge
            PR: ready for review
            Status: awaiting feedback
            Status: has merge conflict
            Status: triage

  on-pr-close:
    permissions:
      pull-requests: write # To remove PR labels.

    if: github.repository_owner == 'PHPCompatibility' && github.event_name == 'pull_request_target' && github.event.pull_request.merged == false

    name: Clean up labels on PR close
    runs-on: ubuntu-latest

    steps:
      - uses: mondeja/remove-labels-gh-action@b7118e4ba5dca74acf1059b3cb7660378ff9ab1a # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            PR: quick merge
            PR: ready for review
            Status: awaiting feedback
            Status: triage

  on-issue-close:
    permissions:
      issues: write # To remove issue labels.

    if: github.repository_owner == 'PHPCompatibility' && github.event.issue.state == 'closed'

    name: Clean up labels on issue close
    runs-on: ubuntu-latest

    steps:
      - uses: mondeja/remove-labels-gh-action@b7118e4ba5dca74acf1059b3cb7660378ff9ab1a # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Status: awaiting feedback
            Status: good first issue
            Status: needs investigation
            Status: to be implemented
            Status: triage
